/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class RDPScreenRecord */

#ifndef _Included_RDPScreenRecord
#define _Included_RDPScreenRecord
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     RDPScreenRecord
 * Method:    frameRate
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_RDPScreenRecord_frameRate
  (JNIEnv *, jobject);

/*
 * Class:     RDPScreenRecord
 * Method:    findDisplays
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_RDPScreenRecord_findDisplays
  (JNIEnv *, jobject);

/*
 * Class:     RDPScreenRecord
 * Method:    selectCaptureDisplay
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_RDPScreenRecord_selectCaptureDisplay
  (JNIEnv *, jobject);

/*
 * Class:     RDPScreenRecord
 * Method:    startRecord
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_RDPScreenRecord_startRecord
  (JNIEnv *, jobject);

/*
 * Class:     RDPScreenRecord
 * Method:    endRecord
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_RDPScreenRecord_endRecord
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
